INSERT INTO `onlineshoppingdb`.`Categories` VALUES (221, "Mobile Phones");
INSERT INTO `onlineshoppingdb`.`Categories` VALUES (231, "Fashion");
INSERT INTO `onlineshoppingdb`.`Categories` VALUES (241, "Home");
INSERT INTO `onlineshoppingdb`.`Categories` VALUES (251, "School");
INSERT INTO `onlineshoppingdb`.`Categories` VALUES (261, "Books");
INSERT INTO `onlineshoppingdb`.`Categories` VALUES (271, "Groceries");

INSERT INTO `onlineshoppingdb`.`Products` VALUES (1001,false ,"iPhone 6S", 699, 221);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1002,false , "Samsung Galaxy", 299, 221);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1003,false , "Designer Skirt", 49, 231);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1004,false , "Jeans", 78.99, 231);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1005,false , "Scarf", 19.99, 231);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1006,false , "Belt", 9.99, 231);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1007,false , "Sprinkler", 89, 241);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1008,false , "Notebook", 9, 251);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1009,false , "Pen", 4.99, 251);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1010,false , "Diary of a Wipy kid", 5.99, 261);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1011,false , "Awful Aunties", 3.99, 261);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1012,false , "Timmy Failure", 4.99, 261);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1013,false , "Apples", 2.99, 271);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1014,false , "Oranges", 1.29, 271);
INSERT INTO `onlineshoppingdb`.`Products` VALUES (1015,false , "Lemons", 0.99, 271);